[cd]
auto_cd_on_add = true
launch_shell = false

[finder]
preview = true

[naming]
template = '{{.Owner}}/{{.Repository}}/{{.Branch}}'

[naming.sanitize_chars]
'/' = '-'
':' = '-'

[ui]
icons = true
tilde_home = true

[worktree]
auto_mkdir = true
basedir = '~/Projects/worktrees'
