# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAE8E3
background         #1C1B1F
cursor             #A59597

active_tab_foreground     #1C1B1F
active_tab_background     #FAE8E3
inactive_tab_foreground   #FAE8E3
inactive_tab_background   #1C1B1F

active_border_color   #FAE8E3
inactive_border_color #1C1B1F
bell_border_color     #173750

color0      #424246
color1		#173750
color2		#3C3239
color3		#6E5858
color4		#627282
color5		#AA867D
color6		#B48E83
color7		#EFD6CE
color8		#A79690
color9		#1E496B
color10		#50434C
color11		#927675
color12		#8298AD
color13		#E2B3A6
color14		#EFBDAE
color15		#EFD6CE
