os:
  editPreset: "nvim-remote"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers --features=github-dark-contrast
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a5d6ff"
      - "bold"
    unstagedChangesColor:
      - "#f85149"
    selectedLineBgColor:
      - "#264f78"
    searchingActiveBorderColor:
      - "#a5d6ff"
      - "bold"
    optionsTextColor:
      - "#b776fc"
    defaultFgColor:
      - "#ffffff"
    cherryPickedCommitFgColor:
      - "#b776fc"
    cherryPickedCommitBgColor:
      - "#f4f4f4"
