
# (re-)generates the `hardware-configuration.nix` file for that `host`
[arg('host', pattern='pc|framework-laptop|lenovo-laptop|pi')]
generate_hardware_configuration host:
	sudo nixos-generate-config --show-hardware-config > ./hosts/{{host}}/hardware-configuration.nix

# installs the configuration of the `host` configuration
[arg('host', pattern='pc|framework-laptop|lenovo-laptop|pi')]
install host:
	sudo nixos-rebuild switch --flake .#{{host}}

build_bwcloud_qcow2:
	nix build .#bwcloud-qcow2 -o bwcloud-qcow2
	@echo "qcow2 file is in ./bwcloud-qcow2/nixos.qcow2"

# formats all .nix files with nixfmt
fmt:
	nixfmt ./**.nix
