# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c66c7c53-2856-4113-8618-cf1b306ad5cd";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-c66c7c53-2856-4113-8618-cf1b306ad5cd".device = "/dev/disk/by-uuid/c66c7c53-2856-4113-8618-cf1b306ad5cd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F695-1893";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c03d8d38-b843-49fc-b813-9538f7297527"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
