# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-416f04f2-c855-4ed4-9b1b-47c668e5b49a";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-416f04f2-c855-4ed4-9b1b-47c668e5b49a".device = "/dev/disk/by-uuid/416f04f2-c855-4ed4-9b1b-47c668e5b49a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D12D-A51F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ed8bb8e6-65ba-4561-9c7d-fb0715d929e0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
